# Generated by Django 5.0 on 2023-12-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_savecheckout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='savecheckout',
        ),
    ]
