# Generated by Django 5.0 on 2023-12-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_savecheckout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='savecartdb',
        ),
    ]
