# Generated by Django 5.0 on 2023-12-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_savecartdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='savecheckout',
        ),
    ]
